name: BlockCmdPE
main: Vaivez66\BlockCmdPE\BlockCmd
version: 1.0.0
api: [1.12.0, 2.0.0, 3.0.1, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
load: POSTWORLD
author: Zeao
description: "Block some commands!"
permissions:
  block.cmd.pe.bypass:
    description: 'Permission to bypass from blocking'
    default: op
