name: BlockCmdPE
main: Vaivez66\BlockCmdPE\BlockCmd
version: 1.0.0
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0, 3.0.1]
load: POSTWORLD
authors: [Vaivez66, Zeao]
description: "Block some commands!"
permissions:
  block.cmd.pe.bypass:
    description: 'Permission to bypass from blocking'
    default: op
